### PR TITLE
fix: resolved all the warnings

### LINKED ISSUE #152: BUGS: Resolve all the warnings when running test
```
 ./src/components/ui/features/adminLogin/AdminLogin.styled.tsx
feedahelp:lint: 1:8  Warning: 'React' is defined but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint: 4:7  Warning: 'rotateBackground' is assigned a value but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint:
feedahelp:lint: ./src/components/ui/features/errors/Forbidden.test.tsx
feedahelp:lint: 11:11  Warning: 'message' is assigned a value but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint:
feedahelp:lint: ./src/components/ui/features/errors/ServerError.test.tsx
feedahelp:lint: 2:18  Warning: 'fireEvent' is defined but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint:
feedahelp:lint: ./src/components/ui/features/errors/ServiceUnavailable.tsx
feedahelp:lint: 8:68  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
feedahelp:lint:
feedahelp:lint: ./src/components/ui/features/header/navbar/Navbar.tsx
feedahelp:lint: 4:10  Warning: 'GenericButton' is defined but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint: 6:8  Warning: 'router' is defined but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint: 14:9  Warning: 'openModal' is assigned a value but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint: 25:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
feedahelp:lint: 26:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
feedahelp:lint: 27:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
feedahelp:lint:
feedahelp:lint: ./src/pages/_error.tsx
feedahelp:lint: 1:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
feedahelp:lint: 7:10  Warning: 'FC' is defined but never used.  @typescript-eslint/no-unused-vars
feedahelp:lint:
feedahelp:lint: ./src/pages/admin.tsx
feedahelp:lint: 3:10  Warning: 'MainPage' is defined but never used.  @typescript-eslint/no-unused-vars
```

### PR DESCRIPTION
**Pull request by Rakibs511**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #152

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx [hunk 1]
```diff
@@ -22,9 +18,9 @@ const NewNav = () => {
             avatar={"/assets/avatar.png"}
             className="img-rotate-button"
           >
-            <img className="outer ring" alt="" />
-            <img className="center ring" alt="" />
-            <img className="inner ring" alt="" />
+            <Image src="" className="outer ring" alt="" />
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx:21]: these will complain for `width` and `height`

File: apps/feedahelp/src/components/ui/features/errors/Forbidden.test.tsx [hunk 2]
```diff
@@ -8,7 +8,7 @@ describe('Forbidden Component', () => {
     const { getByText, getByAltText } = render(<Forbidden />);
     
     const title = getByText("No permission");
-    const message = getByText(/The page you are trying access has restricted access.*Please Login First./);
+    getByText(/The page you are trying access has restricted access.*Please Login First./);
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/errors/Forbidden.test.tsx]: u sure about this, does this work. it seem how are you using this? you are not keeoing it in temp variables anymore?

**Review by TanvirAlam — APPROVED** [review]

**Review by TanvirAlam — CHANGES_REQUESTED** [review]
do the changes

File: apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx (hunk 1 above)
Comment (Rakibs511) [reply apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx:21]: sir yes I know but I understand how much height and width to give

File: apps/feedahelp/src/components/ui/features/errors/Forbidden.test.tsx (hunk 2 above)
Comment (Rakibs511) [reply apps/feedahelp/src/components/ui/features/errors/Forbidden.test.tsx]: this line is not needed because this line just gets the text and does not check anything so we can remove all this line or we can add expect(removedVariable).toBeInTheDocument();

Comment (TanvirAlam) [reply apps/feedahelp/src/components/ui/features/errors/Forbidden.test.tsx]: then delete it

File: apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx (hunk 1 above)
Comment (TanvirAlam) [reply apps/feedahelp/src/components/ui/features/header/navbar/Navbar.tsx:21]: ok we will take care later

**Review by TanvirAlam — CHANGES_REQUESTED** [review]
do the changes

**Review by TanvirAlam — APPROVED** [review]
LGTM, lets merge this sand see what happens

**Review by urmirahman — APPROVED** [review]
LGTM
