### PR TITLE
fix: add icon on searchbar in deshiMenus

### LINKED ISSUE #263: BUGS: Add magnifying icon in both search box
Image

### PR DESCRIPTION
**Pull request by ND-Morsalin**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #263 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx [hunk 1]
```diff
@@ -1,17 +1,28 @@
...
+import { uuidv4 } from '../../utils/uuid'
 
 type IngredientSearchInputProps = {
   id: string
   imgSrc: string
   imgAlt: string
 }
 
+const SearchIcon = () => (
+  <div className=''>
```
Comment (TanvirAlam) [inline packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx:14]: why empty class?

**Review by TanvirAlam — APPROVED** [review]
LGTM
