### PR TITLE
fix: Update the language selector with flags

### LINKED ISSUE #232: BUGS: Update the language selector with flags
Image

### PR DESCRIPTION
**Pull request by Rakibs511**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #232 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/header/languageDropdown/LanguageSelections.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ const LanguageSelections: React.FC = () => {
               }`}
               onClick={() => handleItemClick(item.language)}
             >
+              <img className="w-7 mr-3" src={getFlagSrc(item.country)} alt="" />
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/header/languageDropdown/LanguageSelections.tsx]: use nextjs `import Image from 'next/image'`

File: apps/feedahelp/src/components/ui/features/header/languageDropdown/language.json [hunk 2]
```diff
@@ -1,17 +1,24 @@
...
+        "language": "Deutsch",
+        "country":"DE"
+        
     },
     {
-        "language": "Danish"
+        "language": "Danish",
+        "country":"DK"
     }
 ]
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/header/languageDropdown/language.json]: Add new line, as we will use this in the future

File: apps/feedahelp/src/components/ui/features/header/languageDropdown/LanguageSelections.tsx (hunk 1 above)
Comment (TanvirAlam) [reply apps/feedahelp/src/components/ui/features/header/languageDropdown/LanguageSelections.tsx]: make alt is not empty

**Review by TanvirAlam — CHANGES_REQUESTED** [review]
do the small changes

**Review by TanvirAlam — APPROVED** [review]
LGTM
