### PR TITLE
230 bugs update the sponsor section

### LINKED ISSUE #230: BUGS: Update the sponsor section
Image

### PR DESCRIPTION
**Pull request by ND-Morsalin**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #230 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx [hunk 1]
```diff
@@ -1,22 +1,28 @@
...
 
 const Sponsors = () => {
   return (
     <div className="mb-2 border">
       <div className="container mx-auto p-4">
-        <div className="grid grid-cols-3 gap-4">
+        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 ">
           {items.map((value, index) => (
-            <Styled.bgCover key={index}>
+            // <Styled.bgCover key={index}>
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx]: what is this? delete

File: apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx [hunk 2]
```diff
@@ -1,22 +1,28 @@
...
-                width={200}
-                height={200}
+                width={150}
+                height={150}
+                className={`rounded-full md:w-[150px] md:h-[150px] w-[110px] h-[110px]`}
               />
-            </Styled.bgCover>
+              <CircularText text={value.text} />
+            </div>
+            // </Styled.bgCover>
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx]: what is this? delete

File: apps/feedahelp/src/components/ui/features/sponsors/circularText/circularText.tsx [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+interface CircularTextProps {
+  text: string;
+}
+
+const CircularText: FC<CircularTextProps> = ({ text }) => {
+  const chars = text.split("");
+  const [rotation, setRotation] = useState(12);
+  const [transformOrigin, setTransformOrigin] = useState(75);
+  useEffect(() => {
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/circularText/circularText.tsx:12]: change it in to so
```
useEffect(() => {
  const handleResize = () => {
    const rotationValue = window.innerWidth >= 768 ? 10 : 12;
    const transformOriginValue = window.innerWidth >= 768 ? 100 : 75;
    
    setRotation(rotationValue);
    setTransformOrigin(transformOriginValue);
  };

  // Initial setup
  handleResize();

  // Event listener for window resize
  window.addEventListener("resize", handleResize);

  // Clean up the event listener on unmount
  return () => {
    window.removeEventListener("resize", handleResize);
  };
}, []);
```

File: apps/feedahelp/src/components/ui/features/sponsors/circularText/circularText.tsx [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+      } else {
+        setRotation(12);
+        setTransformOrigin(75);
+      }
+  }, []);
+
+  return (
+    <div className="text absolute h-full w-full animate-spin-slow text-black">
+      <p>
+        {chars.map((char, i) => (
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/circularText/circularText.tsx]: Make it more read able
```
{chars.map((char, i) => {
      const rotationValue = i * rotation;
      const transformOriginValue = `0 ${transformOrigin}px`;

      const charStyle = {
        transform: `rotate(${rotationValue}deg)`,
        transformOrigin: transformOriginValue,
      };

      return (
        <span
          className="absolute left-1/2 text-sm md:text-xl"
          style={charStyle}
          key={i}
        >
          {char}
        </span>
      );
    })}
    ```

File: apps/feedahelp/tailwind.config.ts [hunk 5]
```diff
@@ -20,7 +20,10 @@ export default {
         '15': '15',
         '16': '16',
         '17': '17',
-      }
+      },
+      animation: {
```
Comment (TanvirAlam) [inline apps/feedahelp/tailwind.config.ts]: you are adding a simple animation to `Tailwind.config`? r u gone mental?
or you want to distroy it.

put somewhere else

**Review by TanvirAlam — CHANGES_REQUESTED** [review]
do the changes

File: apps/feedahelp/tailwind.config.ts [hunk 6]
```diff
@@ -20,7 +20,8 @@ export default {
         '15': '15',
         '16': '16',
         '17': '17',
-      }
+      },
+
```
Comment (TanvirAlam) [inline apps/feedahelp/tailwind.config.ts]: you are adding new line and a comma

Comment (TanvirAlam) [reply apps/feedahelp/tailwind.config.ts]: delete them

File: apps/feedahelp/src/components/ui/features/sponsors/circularText/circular.styled.tsx [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+  }
+  100% {
+    transform: rotate(360deg);
+  }
+`;
+
+export const  RotatingDiv = styled.div`
+/* Apply the animation */
+animation: ${spinSlow} 5s linear infinite;
+`;
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/circularText/circular.styled.tsx]: New line please

File: apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx [hunk 8]
```diff
@@ -1,22 +1,26 @@
...
 const Sponsors = () => {
   return (
     <div className="mb-2 border">
       <div className="container mx-auto p-4">
-        <div className="grid grid-cols-3 gap-4">
+        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 ">
           {items.map((value, index) => (
-            <Styled.bgCover key={index}>
+            <div
+              className="relative flex h-[150px] w-[150px] md:h-[200px] md:w-[200px] items-center justify-center mx-auto duration-300 transform hover:scale-110"
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/sponsors/Sponsors.tsx]: this is too long move it to `global.css`

**Review by TanvirAlam — CHANGES_REQUESTED** [review]

**Review by TanvirAlam — APPROVED** [review]
LGTM lets how it looks
