### PR TITLE
fix: z-index-issue-when-payment-MODAL-open-from-Deshi-Menu-search

### LINKED ISSUE #379: BUGS: z-index issue when payment MODAL open from Deshi Menu search
Image

### PR DESCRIPTION
**Pull request by Rakibs511**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #379 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/deshiMenus/DeshiMenus.tsx [hunk 1]
```diff
@@ -23,6 +25,15 @@ type DeshiMenuProps = {
...
   const [DeshiMenus, setDeshiMenus] = useState<DeshiMenuProps[]>([]);
+  const [modalOpen, setModalOpen] = useState(false);
+
+  const closeModal = (): void => {
+    setModalOpen(false);
+  };
+
+  const openModal = (): void => {
+    setModalOpen(true);
+  };
```
Comment (MNSM92) [inline apps/feedahelp/src/components/ui/features/deshiMenus/DeshiMenus.tsx:36]: what if we just pass the setModalOpen to the children??

**Review by MNSM92 — COMMENTED** [review]
Good One.

File: apps/feedahelp/src/components/ui/features/deshiMenus/DeshiMenus.tsx (hunk 1 above)
Comment (Rakibs511) [reply apps/feedahelp/src/components/ui/features/deshiMenus/DeshiMenus.tsx:36]: yeah, we can but just easy to understand. it will change when we implement redux its comming

**Review by TanvirAlam — APPROVED** [review]
LGTM
