### PR TITLE
312 error fix

### LINKED ISSUE #312: BUGS: Clear all the ERROS and Wearning in Develop branch
```
lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3
(anonymous) @ lockdown-run.js:17
Show 1 more frame
Show less
lockdown-more.js:99 Protecting intrinsics failed: ReferenceError: harden is not defined
  at lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (lockdown-more.js:44:22)
  at lockdown-more.js:97:5
(anonymous) @ lockdown-more.js:99
Show 1 more frame
Show less
script.072ad72b.js:1341 General Content Script Loaded.
client.js:1 Warning: Prop `htmlFor` did not match. Server: "input-search-field-aaa792b5-4cef-4795-b95b-c8af89fd175a" Client: "input-search-field-89d61f05-ea3f-48a8-8243-384c351d978c"
    at label
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at IngredientSearchInput
    at form
    at div
    at div
    at StickyBox (webpack-internal:///../../node_modules/.pnpm/react-sticky-box@2.0.4_react@18.2.0/node_modules/react-sticky-box/dist/index.js:283:11)
    at div
    at div
    at div
    at Ingredients (webpack-internal:///./src/components/ui/features/ingredients/Ingredients.tsx:21:90)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at MainPage
    at div
    at main
    at div
    at ThemeProvider (webpack-internal:///../../packages/ui/components/contexts/ThemeContext.tsx:21:11)
    at Layout (webpack-internal:///./src/components/Layouts/Layout.tsx:16:11)
    at Index
    at CmsContextProvider (webpack-internal:///../../packages/ui/components/contexts/CmsContext.tsx:20:11)
    at LoadingContextProvider (webpack-internal:///../../packages/ui/components/contexts/LoadingContext.tsx:19:11)
    at SessionProvider (webpack-internal:///../../node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_nodemailer@6.9.5_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/react/index.js:455:24)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:26:11)
    at AppWithTranslation (webpack-internal:///../../node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.0_next@13.4.2_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/esm/appWithTranslation.js:34:22)
    at Hydrate (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs:31:3)
    at QueryClientProvider (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at TRPCProvider (webpack-internal:///../../node_modules/.pnpm/@trpc+react-query@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+server@10.3_ivjpmxuue3yys6gh4nrzrzmj5y/node_modules/@trpc/react-query/dist/createHooksInternal-7ba6fd69.mjs:214:17)
    at WithTRPC (webpack-internal:///../../node_modules/.pnpm/@trpc+next@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+react-query@10.38._76fp2dbf5ugh4s2isj6vllxpka/node_modules/@trpc/next/dist/index.mjs:42:83)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:305:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:854:919)
    at Container (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:77:1)
    at AppContainer (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:206:11)
    at Root (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:384:11) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForPropDifference @ react-dom.development.js:9571
diffHydratedProperties @ react-dom.development.js:10414
hydrateInstance @ react-dom.development.js:11306
prepareToHydrateHostInstance @ react-dom.development.js:12564
completeWork @ react-dom.development.js:22181
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
12client.js:1 Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at Cta (webpack-internal:///./src/components/ui/features/deshiMenus/Cta/Cta.tsx:13:92)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at div
    at div
    at div
    at DeshiMenus
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at MainPage
    at div
    at main
    at div
    at ThemeProvider (webpack-internal:///../../packages/ui/components/contexts/ThemeContext.tsx:21:11)
    at Layout (webpack-internal:///./src/components/Layouts/Layout.tsx:16:11)
    at Index
    at CmsContextProvider (webpack-internal:///../../packages/ui/components/contexts/CmsContext.tsx:20:11)
    at LoadingContextProvider (webpack-internal:///../../packages/ui/components/contexts/LoadingContext.tsx:19:11)
    at SessionProvider (webpack-internal:///../../node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_nodemailer@6.9.5_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/react/index.js:455:24)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:26:11)
    at AppWithTranslation (webpack-internal:///../../node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.0_next@13.4.2_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/esm/appWithTranslation.js:34:22)
    at Hydrate (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs:31:3)
    at QueryClientProvider (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at TRPCProvider (webpack-internal:///../../node_modules/.pnpm/@trpc+react-query@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+server@10.3_ivjpmxuue3yys6gh4nrzrzmj5y/node_modules/@trpc/react-query/dist/createHooksInternal-7ba6fd69.mjs:214:17)
    at WithTRPC (webpack-internal:///../../node_modules/.pnpm/@trpc+next@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+react-query@10.38._76fp2dbf5ugh4s2isj6vllxpka/node_modules/@trpc/next/dist/index.mjs:42:83)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:305:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:854:919)
    at Container (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:77:1)
    at AppContainer (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:206:11)
    at Root (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:384:11)
console.error @ client.js:1
window.console.error @ next-dev.js:27
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
checkControlledValueProps @ react-dom.development.js:1592
initWrapperState @ react-dom.development.js:1775
diffHydratedProperties @ react-dom.development.js:10234
hydrateInstance @ react-dom.development.js:11306
prepareToHydrateHostInstance @ react-dom.development.js:12564
completeWork @ react-dom.development.js:22181
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "/static/images/feedahelp/logo.png" was detected as the Largest Contentful Paint (LCP). Please add the "priority" property if this image is above the fold.
Read more: https://nextjs.org/docs/api-reference/next/image#priority
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:525
general.js:102 Only one LaunchDarklyClient can exist at a time, but another client already exists.  This probably means something has gone wrong with our DI system, or we're using it incorrectly.
d @ general.js:102
j @ general.js:299
await in j (async)
Z @ general.js:299
await in Z (async)
(anonymous) @ general.js:299
await in (anonymous) (async)
l.a @ general.js:573
17469 @ general.js:299
l @ general.js:573
(anonymous) @ general.js:573
(anonymous) @ general.js:573
Show 9 more frames
Show less
6client.js:1 Image is missing required "alt" property. Please add Alternative Text to describe the image for screen readers and search engines. 
    at img
    at eval (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/image.js:231:11)
    at eval (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/image.js:305:11)
    at span
    at div
    at div
    at div
    at O (webpack-internal:///../../node_modules/.pnpm/styled-components@5.3.9_@babel+core@7.22.9_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19767)
    at CounterDisplay (webpack-internal:///./src/components/ui/features/fahCounter/FAHCounterDisplay.tsx:18:11)
    at div
    at FAHCounter (webpack-internal:///./src/components/ui/features/fahCounter/FAHCounter.tsx:15:90)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///../../node_modules/.pnpm/@mui+material@5.13.5_@emotion+react@11.11.1_@emotion+styled@11.11.0_@types+react@18.2.6_react-dom@18.2.0_react@18.2.0/node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at MainPage
    at div
    at main
    at div
    at ThemeProvider (webpack-internal:///../../packages/ui/components/contexts/ThemeContext.tsx:21:11)
    at Layout (webpack-internal:///./src/components/Layouts/Layout.tsx:16:11)
    at Index
    at CmsContextProvider (webpack-internal:///../../packages/ui/components/contexts/CmsContext.tsx:20:11)
    at LoadingContextProvider (webpack-internal:///../../packages/ui/components/contexts/LoadingContext.tsx:19:11)
    at SessionProvider (webpack-internal:///../../node_modules/.pnpm/next-auth@4.22.1_next@13.4.2_nodemailer@6.9.5_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/react/index.js:455:24)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:26:11)
    at AppWithTranslation (webpack-internal:///../../node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.0_next@13.4.2_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/esm/appWithTranslation.js:34:22)
    at Hydrate (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/Hydrate.mjs:31:3)
    at QueryClientProvider (webpack-internal:///../../node_modules/.pnpm/@tanstack+react-query@4.35.0_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at TRPCProvider (webpack-internal:///../../node_modules/.pnpm/@trpc+react-query@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+server@10.3_ivjpmxuue3yys6gh4nrzrzmj5y/node_modules/@trpc/react-query/dist/createHooksInternal-7ba6fd69.mjs:214:17)
    at WithTRPC (webpack-internal:///../../node_modules/.pnpm/@trpc+next@10.38.1_@tanstack+react-query@4.35.0_@trpc+client@10.38.1_@trpc+react-query@10.38._76fp2dbf5ugh4s2isj6vllxpka/node_modules/@trpc/next/dist/index.mjs:42:83)
    at PathnameContextProviderAdapter (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:305:63)
    at ReactDevOverlay (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:854:919)
    at Container (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:77:1)
    at AppContainer (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:206:11)
    at Root (webpack-internal:///../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/index.js:384:11)
console.error @ client.js:1
window.console.error @ next-dev.js:27
overrideMethod @ console.js:213
eval @ image.js:274
commitAttachRef @ react-dom.development.js:23645
commitLayoutEffectOnFiber @ react-dom.development.js:23503
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "/icons/currencyIcon.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
diffHydratedProperties @ react-dom.development.js:10224
hydrateInstance @ react-dom.development.js:11306
prepareToHydrateHostInstance @ react-dom.development.js:12564
completeWork @ react-dom.development.js:22181
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/caf473f4c94fbb175ba834421beb4ef363bc142d-3144x3026.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
diffHydratedProperties @ react-dom.development.js:10224
hydrateInstance @ react-dom.development.js:11306
prepareToHydrateHostInstance @ react-dom.development.js:12564
completeWork @ react-dom.development.js:22181
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "/static/images/feedahelp/logo.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
eval @ image.js:278
commitAttachRef @ react-dom.development.js:23645
commitLayoutEffectOnFiber @ react-dom.development.js:23503
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/73127aa2afee1b9c4690de8d1ad003ba9696049e-3133x2953.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/ace1bf2434a67266c03b688019557a15090252f8-3133x3694.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/ef82b1aff553f30274fa7790076e386bef5310ad-3133x3369.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/6ac8c3823a1336a681eca2440a812627a23fa2a2-3133x2990.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/737f8f0925fc613a6cb1804d1b90d54069c8004a-428x516.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/ea3fac7466e307e4bee69aae02f28eb9ce53e506-333x424.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/1a208b3e055acff35b324c8f4a9a387cad66fabd-699x729.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/14390865ffc19f37084fb87a0eec5969fce9ea6a-1088x674.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/306a688b19d83602fa6b38291afd49bd3d779f6b-540x460.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/4526dd360fe6c56706fc7a5655096e768eb92086-720x346.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/4727432b5c63adf2cb8715153c06f726eccee6bf-512x385.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/1e88bf92d3218bb35df658f6b1634d122e0eb4cc-750x500.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/95af0641dea6905a13f7d7ab89d0609bc3a4a735-488x542.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/58d8e4bca3f896ef6bd90404b7b38d9b5a07f343-1500x2000.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/739c0bf45492a375ead20fb58b350cbe59458be0-700x350.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/137c38ecdaeb29065bb21cd9b4a6e1b1764a36c2-521x479.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
warn-once.js:16 Image with src "https://cdn.sanity.io/images/s98tqz9i/production/659d5bab5e55733f12155403fc2b31d1562257dd-471x529.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
overrideMethod @ console.js:213
warnOnce @ warn-once.js:16
eval @ image.js:211
Promise.then (async)
handleLoading @ image.js:141
onLoad @ image.js:292
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
load (async)
addEventBubbleListener @ react-dom.development.js:6687
addTrappedEventListener @ react-dom.development.js:9191
listenToNonDelegatedEvent @ react-dom.development.js:9112
setInitialProperties @ react-dom.development.js:9876
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### PR DESCRIPTION
**Pull request by MNSM92**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #312

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/hero/Hero.tsx [hunk 1]
```diff
@@ -60,9 +60,9 @@ const Hero = () => {
 
     return () => {
       window.removeEventListener("resize", handleResize);
-      clearInterval(autoScrollRef.current as any);
+      clearInterval(autoScrollRef.current as NodeJS.Timeout);
     };
-  }, []);
+  });
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/hero/Hero.tsx]: We put an empty [], if we want the code inside useEffect to run only once. Without empty [], the code inside the useEffect will run on every render

File: packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx [hunk 2]
```diff
@@ -20,8 +20,8 @@ const IngredientSearchInput = () => {
   return (
     <Styled.SearchBoxContainer>
       <Styled.SearchBox>
-        <label htmlFor={id}><Styled.SearchIcons /></label>
-        <Styled.SearchInput id={id} type='text' className='input-search' placeholder='Type to Search...' />
+        <label htmlFor="input-search-field"><Styled.SearchIcons /></label>
+        <Styled.SearchInput id="input-search-field" type='text' className='input-search' placeholder='Type to Search...' />
```
Comment (TanvirAlam) [inline packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx]: you broke Search input box, test it out.

now you se the is both working the same

**Review by TanvirAlam — CHANGES_REQUESTED** [review]

File: apps/feedahelp/src/pages/api/auth/[...nextauth].ts [hunk 3]
```diff
@@ -53,12 +52,12 @@ export const authOptions: NextAuthOptions = {
         const user = {
           ...credentials,
         };
```
Comment (MohiuddinRU) [inline apps/feedahelp/src/pages/api/auth/[...nextauth].ts]: Nice to know: 
Complexity of Spread Operator is O(n). That means it will iterate over all elements of the array. We could have object assignment which is of O(1). 

Ref: https://stackoverflow.com/questions/57032373/whats-the-time-complexity-of-javascript-spread-syntax-in-arrays

File: packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx (hunk 2 above)
Comment (MNSM92) [reply packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx]: I have solved it

File: apps/feedahelp/src/pages/api/auth/[...nextauth].ts (hunk 3 above)
Comment (MNSM92) [reply apps/feedahelp/src/pages/api/auth/[...nextauth].ts]: check it

File: apps/feedahelp/src/components/ui/features/hero/Hero.tsx (hunk 1 above)
Comment (MNSM92) [reply apps/feedahelp/src/components/ui/features/hero/Hero.tsx]: done.

**Review by TanvirAlam — APPROVED** [review]

File: packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx [hunk 4]
```diff
@@ -6,22 +6,22 @@ import { uuidv4 } from '../../utils/uuid'
...
 
 const SearchIcon = () => (
   <div className=''>
     <Icon icon={search} size={24} />
   </div>
 )
-const IngredientSearchInput = () => {
-  const id = `input-search-field-${uuidv4()}`
+const IngredientSearchInput = ({ id, imgSrc, imgAlt }: IngredientSearchInputProps) => {
+  // const id = `input-search-field-${uuidv4()}`
```
Comment (MohiuddinRU) [inline packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx:19]: We can remove the commented codes as it shows our code cleaner.  Besides, we have git to see the previous versions.

File: packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx [hunk 5]
```diff
@@ -6,22 +6,22 @@ import { uuidv4 } from '../../utils/uuid'
...
   return (
     <Styled.SearchBoxContainer>
       <Styled.SearchBox>
-        <label htmlFor="input-search-field"><Styled.SearchIcons /></label>
-        <Styled.SearchInput id="input-search-field" type='text' className='input-search' placeholder='Type to Search...' />
+        <label htmlFor={id}><Styled.SearchIcons /></label>
```
Comment (MohiuddinRU) [inline packages/ui/components/elements/IngredientSearchInput/IngredientSearchInput.tsx:23]: Previous was better. Generalization makes our code hard to understand.
