### PR TITLE
fix: added glassy background

### LINKED ISSUE #286: BUGS: Hero main image logo add glassy background
Image

### PR DESCRIPTION
**Pull request by sojib-mondol**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #286 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/feedahelp/src/components/ui/features/hero/Hero.tsx [hunk 1]
```diff
@@ -191,7 +191,7 @@ const Hero = () => {
                     src={urlForThumbnail(item.image)}
                     alt="hero-image"
                   />
-                  <div className="absolute top-1 z-0">
+                  <div className="absolute top-1 z-12">
```
Comment (TanvirAlam) [inline apps/feedahelp/src/components/ui/features/hero/Hero.tsx:194]: `z-12` means its on top of everything, open login MODAL and see?

**Review by TanvirAlam — CHANGES_REQUESTED** [review]

File: apps/feedahelp/src/components/ui/features/hero/Hero.tsx (hunk 1 above)
Comment (TanvirAlam) [reply apps/feedahelp/src/components/ui/features/hero/Hero.tsx:194]: never mind

**Review by TanvirAlam — APPROVED** [review]
